apiVersion: apps/v1
kind: Deployment
metadata:
  name: intruder
  namespace: intruder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intruder
  template:
    metadata:
      labels:
        app: intruder
    spec:
      containers:
      - name: nginx
        image: nginx